version: '3.4'

services:
  go-eventstore-query:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SOURCE_REPO: go-agg-inventory-cmd

  go-inventory:
    image: go-agg-inventory-cmd_go-eventstore-query

